Promise.reject(new Error('Some error')).catch(e => console.log(e.message));